# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go mod tidy && go build -o ./tmp/main ."
  bin = "./tmp/main"
  exclude_dir = ["vendor", "tmp", ".git", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  delay = 1000 # ms