version: '3'
services:
  go-dev:
    build: .
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg
    ports:
      - "8448:8448"
    network_mode: "host"
    tty: true
    stdin_open: true

volumes:
  go-mod-cache: